-- PostgreSQL Database Schema for Veterinaria
-- ============================================
-- This schema is auto-generated by Prisma
-- See: prisma/schema.prisma

-- ============ USERS / AUTHENTICATION ============
CREATE TABLE IF NOT EXISTS "users" (
  "idusuario" SERIAL NOT NULL PRIMARY KEY,
  "name" TEXT,
  "lastname" TEXT,
  "email" TEXT NOT NULL UNIQUE,
  "password_hash" TEXT NOT NULL,
  "role" TEXT NOT NULL DEFAULT 'user',
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "password_resets" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "user_id" INTEGER NOT NULL,
  "reset_token" TEXT,
  "expiration_date" TIMESTAMP(3),
  CONSTRAINT "password_resets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("idusuario") ON DELETE CASCADE
);

-- ============ FORMS ============
CREATE TABLE IF NOT EXISTS "formulario" (
  "idformulario" SERIAL NOT NULL PRIMARY KEY,
  "nombre" TEXT,
  "apellido" TEXT,
  "telefono" INTEGER,
  "mail" TEXT,
  "fecha_nacimiento" TEXT,
  "direccion" TEXT,
  "ciudad" TEXT,
  "provincia" TEXT,
  "codigo_postal" INTEGER,
  "pais" TEXT,
  "tipo_documento" TEXT,
  "numero_documento" INTEGER,
  "tipo_vivienda" TEXT NOT NULL,
  "espacio_seguro" TEXT NOT NULL,
  "tiempo_solo" INTEGER NOT NULL,
  "personas_encasa" INTEGER NOT NULL,
  "familia_deacuerdo" TEXT NOT NULL,
  "otras_mascotas_anteriormente" TEXT NOT NULL,
  "tipo" TEXT NOT NULL,
  "eventos" TEXT NOT NULL,
  "otras_mascotas_actualmente" INTEGER NOT NULL,
  "tipo_mascotas_actual" TEXT NOT NULL,
  "recursos" TEXT NOT NULL,
  "vacunar_y_esterilizar" TEXT NOT NULL,
  "encargado_cuidado" TEXT NOT NULL,
  "sitio_animal_solo" TEXT NOT NULL,
  "rol_del_animal" TEXT NOT NULL,
  "estado" TEXT NOT NULL
);

-- ============ PRODUCTS ============
CREATE TABLE IF NOT EXISTS "productos" (
  "idproducto" SERIAL NOT NULL PRIMARY KEY,
  "nombre" TEXT,
  "url_imagen" TEXT,
  "stock" INTEGER NOT NULL
);

-- ============ PURCHASES ============
CREATE TABLE IF NOT EXISTS "compra" (
  "idcompra" SERIAL NOT NULL PRIMARY KEY,
  "producto" INTEGER,
  "unidades" INTEGER,
  "precio" INTEGER,
  CONSTRAINT "compra_producto_fkey" FOREIGN KEY ("producto") REFERENCES "productos" ("idproducto") ON DELETE SET NULL
);

-- ============ ANIMALS ============
CREATE TABLE IF NOT EXISTS "animal" (
  "idanimal" SERIAL NOT NULL PRIMARY KEY,
  "nombre" TEXT,
  "edad" INTEGER,
  "descripcion" TEXT,
  "imagen_m" TEXT,
  "dueño" INTEGER,
  CONSTRAINT "animal_dueño_fkey" FOREIGN KEY ("dueño") REFERENCES "users" ("idusuario") ON DELETE SET NULL
);

-- ============ APPOINTMENTS ============
CREATE TABLE IF NOT EXISTS "turno" (
  "idturno" SERIAL NOT NULL PRIMARY KEY,
  "mascota" INTEGER,
  "motivo" TEXT,
  "fecha" TEXT,
  "estado" TEXT NOT NULL,
  CONSTRAINT "turno_mascota_fkey" FOREIGN KEY ("mascota") REFERENCES "animal" ("idanimal") ON DELETE SET NULL
);

-- ============ PROFILES ============
CREATE TABLE IF NOT EXISTS "perfil" (
  "idperfil" SERIAL NOT NULL PRIMARY KEY,
  "nombre" TEXT,
  "apellido" TEXT,
  "telefono" INTEGER,
  "mail" TEXT,
  "mascota" INTEGER,
  CONSTRAINT "perfil_mascota_fkey" FOREIGN KEY ("mascota") REFERENCES "animal" ("idanimal") ON DELETE SET NULL
);

-- ============ CONSULTATIONS ============
CREATE TABLE IF NOT EXISTS "consultas" (
  "idconsulta" SERIAL NOT NULL PRIMARY KEY,
  "nombre" INTEGER,
  "descripcion" TEXT,
  CONSTRAINT "consultas_nombre_fkey" FOREIGN KEY ("nombre") REFERENCES "perfil" ("idperfil") ON DELETE SET NULL
);

-- ============ MEDICAL HISTORY ============
CREATE TABLE IF NOT EXISTS "historial_medico" (
  "idhistorial" SERIAL NOT NULL PRIMARY KEY,
  "mascota" INTEGER,
  "turnos_pasados" TEXT,
  "vacunas" TEXT,
  CONSTRAINT "historial_medico_mascota_fkey" FOREIGN KEY ("mascota") REFERENCES "animal" ("idanimal") ON DELETE SET NULL
);

-- ============ SESSION MANAGEMENT ============
CREATE TABLE IF NOT EXISTS "session" (
  "sid" VARCHAR NOT NULL PRIMARY KEY,
  "sess" JSON NOT NULL,
  "expire" TIMESTAMP(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS "IDX_session_expire" on "session" ("expire");